### ISSUE TITLE
decrypt error for epub3 (adobe drm)

### ISSUE THREAD

**Issue by mashadbb** [13xforever/DeDRM#3]
I received 4 books from Kobo Desktop
But 2 of them gave an error and the DRM was not removed

When I saw the content of the files of these two books in the Edit Book section of the Caliber software, I noticed that all XHTML, JPG, ... files are apparently encrypted.
Even when I transfer these two books into Epubor and Caliber software, the cover image is not displayed.
When I looked carefully, I realized that the file type of these two books is Epub3 and it uses ADOBE DRM.
I think that these types of books should be DECRYPT first and then DRM removed so that it can be converted to PDF format.
Photo attached.
https://prnt.sc/lfrUGoWspSjc

Thank you for guiding me

**Comment by 13xforever** [comment]
I can't open the screenshot link (you should really upload directly to github), but this is mainly focused on Kobo DRM and older Adobe DRM. You're probably downloading newer Adept3 encrypted files, which is not supported.

Simply download your books in Kobo Desktop, they're stored in `%LocalAppData%\Kobo\Kobo Desktop Edition\kepub` as guids without extension, but it's a regular kepub that should work.

If you're building from sources, then the launcher will search for kepubs automatically.

**Comment by mashadbb** [comment]
All the software I use are up to date
Please see the screenshot
I also uploaded it to GitHub

**[screenshot](https://prnt.sc/lfrUGoWspSjc)**

![adobe drm](https://github.com/13xforever/DeDRM/assets/136791011/92883fe0-09dc-4501-a8fa-a95e57cd5277)

**Comment by 13xforever** [comment]
ok. so you actually have 2 drm-free books and 2 kepubs with kobo drm; does kobo desktop open these two books fine? I had an issue one time when it failed to update the keys and said it needs a reinstall to fix it. If you can read the books fine, then it might've been the latest update, I'll test it tomorrow.

**Comment by mashadbb** [comment]
yes all ebook open in kobo desktop

screenshot and 3 ebooks attached.


<img width="624" alt="kobo desk" src="https://github.com/13xforever/DeDRM/assets/136791011/d0e0efe0-65bc-492b-b6b4-9354799611c5">
<img width="460" alt="kobo desktop" src="https://github.com/13xforever/DeDRM/assets/136791011/4c7f64b6-cdc1-41e7-8419-f555676f4f9d">

**Comment by 13xforever** [comment]
Please do not upload copyrighted materials, the books by themselves are useless, and you'll get in trouble myself, yourself, and github.

I tested my books on the latest kobo desktop update and it works fine, so there's been no changes to the drm itself.

It is problematic to buy new books from kobo for me at the moment, so I can't reproduce the issue exactly, but I'll try poking on weekend or sooner if I'll have some free time.

One thing I *do* notice in your screenshot however, is that you're running dedrm from the zip and as administrator insted of your own user, this won't work. Either properly unpack and run as a normal program (it shouldn't ask for elevation, and you must not run it as administrator explicitly), or better yet, build from sources. Last binary release was two years ago and there's been a lot of changes since. This project is not intended to be a user-friendly ready-to-use tool, it's a research/model code for people to re-implement kobo drm scheme.

EDIT: I've uploaded the [latest build](https://github.com/13xforever/DeDRM/releases/latest), but it may or may not work still.
